### ISSUE TITLE
[CONTRACTS] - Define supplementary incentives for proxy yield farming

### ISSUE THREAD

**Issue by hpiyankov** [ubiquity/uad-ui#119]
Task: Define additional incentives for the proxy yield farming which will also have positive impact on uAD and UBQ

**Comment by hpiyankov** [comment]
We have two main levers in proxy yield farming:
- Reduce the upfront fee
- Increase the bonus yield

We have two tokens that we want to have a positive impact on:
- UBQ
- uAD

From @hpiyankov perspective, the better incentivisation is the increased yield. 
From @pavlovcik perspective, the better incentive is the reduced up-front fee. Thus:

**Task1: Decide which the core incentive is.**

From there we can:

1. Provide yield boost for staking token1 (main incentive)
2. Provide additional yield boost for holding a particular NFT (smaller amount, addition incentive as suggested by @zgorizzo69 )
3. Provide a reduction in the upfront fee for staking token1 (main incentive)

This comment focuses on incentives 1 and 3, however incentive 2, should also be implemented in a flexible way.

The first core question we need to answer is what token is being staked:
- In the case of UBQ, this is pretty straightforward - this should be the UBQ token
- In the case of uAD, we need to decide if this will be:

1. The uAD token itself
2. An LP token for the 3CRV pool
3. Some other system-related, uAD-adjacent tokens such as uDEBT / uAR

Staking debt feels clunky and causes issues with the debt expiration, so my suggestion is that this is out of scope.
Staking uAD directly is OK + we can spin it in an interesting way, such as "If you stake X DAI, you are also allowed to stake up to X uAD and earn the same yield on both". So what we are essentially saying is that you can double your yield by matching your DAI staked amount with uAD staking. The maths would be easy, it is easy to understand and it is not too gimmicky. The core issue here is that it does not feel too much of a gain if you need to match the staked DAI amount in order to double the yield.
Staking LP tokens seems to hold the same benefit as staking uAD directly and it might be a bit harder to grasp. So we can stick the staking uAD.

The core issue with UBQ would be determining the staking amount. E.g. we have two options:
- Requiring a fixed amount of UBQ to be staked (e.g. 5000 tokens = 5% boost for example). The core issue with this one is that in any given situation it might be too cheap or too expensive.
- Requiring a variable amount to be staked based on USD equivalence - but this might be too volatile and requires too much user interaction.

**In lieu of the above, my final suggestion is:**
- Stake UBQ to reduce your up-front fee. We need to come up with the correct amounts. Given that we have just over 1MM UBQ minted, I suggest we go with 100 UBQ per 1% reduction in the deposit fee. So you need to stake 1000 UBQ in order to remove the deposit fee. The UBQ remains staked until you withdraw your principal from the proxy yield farming.
- Stake uAD up to the HALF of DAI staked amount and earn an additional 50% bonus yield on the DAI yield. Example:

1. User staked 10 000 DAI at 10% base yield. We give him 50% bonus so the yield becomes 15% for the DAI
2. He is allowed to stake up to 5 000 uAD, We give him an additional 50% bonus, so the yield becomes 20% for the uAD.

@pavlovcik @zgorizzo69 Opinions?

**Comment by 0x4007** [comment]
> From @pavlovcik perspective, the better incentive is the reduced up-front fee. Thus:

I believe that minimizing the upfront deposit fee will have outsized effects on ape mentality. As a degen myself, I know because I value liquidity, and by that I mean the ability to pull out my funds to ape into the next hot farm at the drop of a hat. If I'm hit with a 10% fee up front I'll feel more trapped and wont be keen to move in significant amounts. 

> 
> **Task1: Decide which the core incentive is.**
> 
> From there we can:
> 
> 1. Provide yield boost for staking token1 (main incentive)

Seems like UBQ has the spotlight for Q4.

> 2. Provide additional yield boost for holding a particular NFT (smaller amount, addition incentive as suggested by @zgorizzo69 )

Let's ride off the coat-tails of Cool Cats NFTs etc. Co-marketing!

> Staking LP tokens seems to hold the same benefit as staking uAD directly and it might be a bit harder to grasp. So we can stick the staking uAD.

You should give more credit to the work that the UI can do for us. In the deposit `<input>` box we can show that you have "xxx LP Tokens Available to Deposit" right? I suppose it could get complex for marketing reasons, but then I suppose the solution would be to have @zapaz do his magic again with another Instadapp macro :)

> **In lieu of the above, my final suggestion is:**
> 
> * Stake UBQ to reduce your up-front fee. We need to come up with the correct amounts. Given that we have just over 1MM UBQ minted, I suggest we go with 100 UBQ per 1% reduction in the deposit fee. So you need to stake 1000 UBQ in order to remove the deposit fee. The UBQ remains staked until you withdraw your principal from the proxy yield farming.

I want to reduce the UBQ emissions rate as a thank you to our early supporters. Not sure what rate to reduce emissions by. I also feel like 1000 UBQ is cheap (I tend to look at UBQ as being valued at $1 nowadays, especially since we're doing a 1:1 compensation match with the contributors valuing it at $1) what do you think about 10000 UBQ?

> * Stake uAD up to the HALF of DAI staked amount and earn an additional 50% bonus yield on the DAI yield. Example:
> 
> 1. User staked 10 000 DAI at 10% base yield. We give him 50% bonus so the yield becomes 15% for the DAI
> 2. He is allowed to stake up to 5 000 uAD, We give him an additional 50% bonus, so the yield becomes 20% for the uAD.
> 
> @pavlovcik @zgorizzo69 Opinions?

Okay so UBQ will allow apes to ape and uAD will allow investors to make more returns. I think its a solid strategy. 

I wish I had improvement suggestions but I feel like I am not able to spend as much time focusing on this as I would like these days.

**Comment by zgorizzo69** [comment]
At the beginning it was about getting some stablecoin collateral and I see here there is a lot of changes and incentivization mechanism there. The less is better I think stablecoins are already hard to grasp and we should better stick to the ape mentality " easy and lucrative " 
I would suggest that we only keep one like staking UBQ seems to be the one to fit best to our goal

**Comment by 0x4007** [comment]
We need reasons for people to purchase uAD to push up the TWAP or else the flywheel will never get turning @zgorizzo69

**Comment by zgorizzo69** [comment]
the reason can be :  it is a stable coin that maintain a peg ..
I have got the feeling that we are trying to achieve too many goals at the same time so we over engineer and complexify what should be straight and simple.

**Comment by 0x4007** [comment]
@hpiyankov what would you say would be the negative repercussions if we exclude the incentive to purchase uAD?

**Comment by 0x4007** [comment]
Spec agreed upon within a Telegram conversation between @zgorizzo69 and I. @hpiyankov your ideas will be implemented!

**Comment by zgorizzo69** [comment]
to make it futur proof I will leave the possibility to adapt the deposit fee so the calculation for the UBQ to stake is a bit different 
 if 10 000 UBQ gives you 10 % then 100 000 UBQ will give you 100%
 1 UBQ give you a reduction of  0.001 % of the deposit fee

**Comment by 0x4007** [comment]
How about staking for insurance?

- User deposits `1000 USDC` (100%) 
- For the sake of this example the yield is 20% (`200 USDC`)
- Default yield premium is 50% (`100 uAR`)
- User stakes 10% of their principle (`10 UBQ` or `uAR`, not sure which makes more sense here) as an insurance premium in case of Pickle smart contract failures and is eligible for another 20% `20 uAR` reward.

I want to incentivize users to stake their money so that we can shift away risks

@hpiyankov @zgorizzo69

**Comment by 0x4007** [comment]
> to make it futur proof I will leave the possibility to adapt the deposit fee so the calculation for the UBQ to stake is a bit different
> if 10 000 UBQ gives you 10 % then 100 000 UBQ will give you 100%
> 1 UBQ give you a reduction of 0.001 % of the deposit fee

My expectation with this version of the Proxy Yield Aggregator is to make it pausable so that we can launch this as a public beta, learn from it, deprecate (pause forever) it and then launch an official version. Besides that, I think we just need full control of the staked funds and possibly the principle deposits as well. @Zequez we also REALLY need a big APY percentage above the deposit portal or else apes wont care. 

We should seriously consider doing some absurd percentage to get eyes on the project in November/December.

@hpiyankov here's an idea: what if we add the depreciating uAR feature, and then have some crazy uAR distribution for the Proxy Yield Aggregator, like a fixed 1M uAR stacked yield per day. The APY will render as some absurdly high number and attract the attention of apes. In this case, if they are incentivized to purchase uAD then the flywheel will surely spin up. Only sustained by our other (hopefully) integrations already completed by this time?

**Comment by 0x4007** [comment]
Still thinking about this insurance idea. @hpiyankov I was wondering if we could offer pseudo "yield" by having people stake their uAR to be used for insurance and it freezing its depreciation during its staking period. 

This would work especially well if a hack caused some type of uAD supply shock and the twap pops up above 1.00. 

But that's a half baked idea and I have no idea at the moment if there would be any type of supply shock which would shoot up the price. I also don't know what mechanism we would use to invoke the redeem and sell of the staked debts to push the price back down. Something to think about.

**Comment by hpiyankov** [comment]
@pavlovcik Insurance is a VERY complex product on its own. We cannot do it "by the way". If you want to do research on insurance let's do it in a separate thread. Its place is not here.

@pavlovcik the uAR idea - it is doable but EXTREMELY gimmicky. If you feel that this is the way, I can do some research on it, but I really feel that this is a borderline scam.

**Comment by 0x4007** [comment]
Scams pump the hardest ser. Yes let's start a new discussion regarding insurance then. 

Guess it's a dunning-Kruger situation for me because staking seems pretty straightforward to me. We would decide if the payout condition is met, and we would just take the money from the stakers. We don't need to do debts but I figured there might be a use case there worth exploring

**Comment by hpiyankov** [comment]
@pavlovcik I don't understand if we have any remaining action points based on your comment.

**Comment by 0x4007** [comment]
Let's chat on the call today high level about the complexities you foresee and then I'll most likely be keen on starting a new GitHub discussion around the insurance idea.

**Comment by hpiyankov** [comment]
@pavlovcik is this one closed or is anything else needed?

**Comment by 0x4007** [comment]
@zgorizzo69 you can close this unless there's any outstanding questions

**Comment by 0x4007** [comment]
# Multi asset withdrawal

I think we should leave open to the user to be able to determine the withdrawal asset (USDC, uAR, or a combination) upon withdrawal for enhanced UX. We can have a slider on the UI. Also, of course, the max USDC the user will be able to withdraw is the amount they farmed with their principle. 

Identical scenario with three different users with different risk tolerances:

### Risk on user
- User deposits 100 000 USDC @ 20% APY
- User waits a year.
- User decides to withdraw 100 000 USDC + 40 000 uAR

### Risk off user
- User deposits 100 000 USDC @ 20% APY
- User waits a year.
- User decides to withdraw 100 000 USDC + 20 000 USDC

### Risk average user
- User deposits 100 000 USDC @ 20% APY
- User waits a year.
- User decides to withdraw 100 000 USDC + 5 000 USDC + 12 500 uAR (The formula for this ratio should be figured out @hpiyankov)
