### ISSUE TITLE
Bonding Shares UI - Add ability to add liquidity to existing shares

### ISSUE THREAD

**Issue by Zequez** [ubiquity/uad-ui#14]
Right now it's not possible to add liquidity with the current UI; the new Bonding UI can be improved with this.

```ts
bondingV2.connect(signer).addLiquidity(amount, bondingShareID, duration)
```

**Comment by 0x4007** [comment]
the bounty should allow for users to add liquidity to each position. this will include some sort of additional button on the ui, as well as the capability to actually do the transaction.

**Comment by 0xautohub** [comment]
Hey @sergfeldman I think this issue is a bit advanced issue rather than #161
Feeling that this is another good choice that I get accustomed to the project
Hope you to assign this issue to me
Thanks

**Comment by sergfeldman** [comment]
@sunny0714 Thanks for the initiative.
At the moment, I suggest waiting for the first feedback from developers on the first bounty.
If everything is ok, then let's move on to the next bounty :)

**Comment by 0xautohub** [comment]
Hey @sergfeldman yeah, okay
Huh, seems I'm too rushing???
Let me wait
Thanks

**Comment by sergfeldman** [comment]
@sunny0714 The initiative and pace are great :)

**Comment by developerfred** [comment]
@pavlovcik Can I work on this bounty?

**Comment by sergfeldman** [comment]
@developerfred There will be a new portion of the bounty soon. No need to take this bounty now.

**Comment by codeawayaks** [comment]
You can assign this to me.

**Comment by sergfeldman** [comment]
> You can assign this to me.

@codeawayaks You commented on 20+ GitHub issues that you want to take it. 
One developer should solve one bounty at a time to minimize blocking other developers to effectively move forward.
Which 1 bounty do you want to take?

**Comment by kgelpes** [comment]
Is the task open? What's the scope now? 

Confused by this conversation @sergfeldman :
> @developerfred There will be a new portion of the bounty soon. No need to take this bounty now.

**Comment by sergfeldman** [comment]
> Confused by this conversation @sergfeldman :
> 
> > @developerfred There will be a new portion of the bounty soon. No need to take this bounty now.

@kgelpes Hello, since then new portions of the bounty became available.

**Comment by sergfeldman** [comment]
> Is the task open? What's the scope now?

@pavlovcik Can you please check whether this bounty is actual?

**Comment by 0x4007** [comment]
We renamed `BondingV2` into `Staking` but other than that I believe that we can still benefit from this feature.

At a high level, we currently only support users adding more liquidity as part of separate staking positions. Completion of this bounty means that a user can add liquidity to existing positions.

As long as @kgelpes you understand the idea I'm happy to assign the bounty to you. 

My fear though is that this may introduce a lot of additional UI elements to the Staking positions table. This bounty will need to be done with careful consideration to the limited screen real estate (particularly on a mobile device.) 

1. A user must be able to find a button to add liquidity to an existing position. 
2. When they press the button, it should display a text input field which reads the user's LP token balance, along with a "max" button, along with some type of execution button.
3. The transaction must be able to function successfully.

Last detail but we're redoing our deployment contracts and it might block the developers ability to render this portion of the UI. Currently the UI is reading different contract method names compared to what is deployed on mainnet currently. So in order to work on this part I believe the developer needs to deploy the contracts locally, and connect the dApp to their local RPC.

**Comment by kgelpes** [comment]
> We renamed `BondingV2` into `Staking` but other than that I believe that we can still benefit from this feature.
> 
> At a high level, we currently only support users adding more liquidity as part of separate staking positions. Completion of this bounty means that a user can add liquidity to existing positions.
> 
> As long as @kgelpes you understand the idea I'm happy to assign the bounty to you.
> 
> My fear though is that this may introduce a lot of additional UI elements to the Staking positions table. This bounty will need to be done with careful consideration to the limited screen real estate (particularly on a mobile device.)
> 
> 1. A user must be able to find a button to add liquidity to an existing position.
> 2. When they press the button, it should display a text input field which reads the user's LP token balance, along with a "max" button, along with some type of execution button.
> 3. The transaction must be able to function successfully.
> 
> Last detail but we're redoing our deployment contracts and it might block the developers ability to render this portion of the UI. Currently the UI is reading different contract method names compared to what is deployed on mainnet currently. So in order to work on this part I believe the developer needs to deploy the contracts locally, and connect the dApp to their local RPC.

I can tackle this task, but I would need more direction on how to run the contracts locally and create positions to add liquidity to

**Comment by 0x4007** [comment]
> how to run the contracts locally and create positions to add liquidity

@0xcodercrane @zgorizzo69 @rndquu @hashedMae may be able to chime in on this

**Comment by molecula451** [comment]
the UI it's getting revamped in a different way, to rely on the diamond this task specs it's not current anymore. Either the task issue should be updated or this should be closed
