### ISSUE TITLE
Yield Aggregator - Fetch current Pickle JAR APY numbers

### ISSUE THREAD

**Issue by Zequez** [ubiquity/uad-ui#32]
Right now the yield aggregator has hardcoded the USDC pickle jar APY from https://app.pickle.finance/jars
We should research how to retrieve the actual APY numbers.

**Comment by 0x4007** [comment]
> Right now the yield aggregator has hardcoded the USDC pickle jar APY from https://app.pickle.finance/jars We should research how to retrieve the actual APY numbers.

https://api.pickle.finance/prod/protocol/pools

```json
  {
    "identifier": "usdc",
    "liquidity_locked": 5543801.38,
    "apy": 16.65,
    "jarApy": 5.59,
    "tokenAddress": "0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48",
    "jarAddress": "0xeb801ab73e9a2a482aa48caca13b1954028f4c94",
    "gaugeAddress": "0x9e1126c51c319A1d31d928DC498c9988C094e793",
    "tokens": 5543801.377852,
    "ratio": 0.9649749323576109,
    "network": "eth"
  }
```

> Although keep in mind that the APY shown comprises 1) the jarApy with 2) the difference coming from the Pickle APY. This Pickle APY (~11%) represents the weighted PICKLE returns of all the deposits (they can be boosted by locking PICKLE, which I assume you won't be doing). The unboosted PICKLE APY is more like 8.62%. A bit hard to represent a range in our API 

> Just making sure you guys have deposited the pTokens in here as well, as this is where the Pickle yield comes from 😁 https://etherscan.io/address/0x9e1126c51c319A1d31d928DC498c9988C094e793#writeContract

**Comment by 0x4007** [comment]
I followed up on this; I forgot we had this issue open.

@larrythecucumber321:

Hey buddy. The live APR (i.e. your exact PICKLE APR) can be seen on the frontend but otherwise, it can be derived through calculations. But if you haven't locked any DILL, then it will be the low number in the range

But the data annoyingly comes from several places, but this hopefully points you in the right direction https://github.com/pickle-finance/pickle-ui/blob/master/containers/Gauges/useJarGaugeApy.ts#L52

Gauges can all be fetched from here https://etherscan.io/address/0x2e57627ACf6c1812F99e274d0ac61B786c19E74f#code

But since you're only interested in USDC, this is the particular gauge https://etherscan.io/address/0x9e1126c51c319A1d31d928DC498c9988C094e793#code
