### ISSUE TITLE
User Experience - Farm Identification

### ISSUE THREAD

**Issue by 0x4007** [ubiquity/uad-ui#53]
I spoke with an acquaintance whos jumping in with little context and he was confused about the two different farms we have on the dashboard currently. 

I suggest we load the page with both farm UI components being minimized and that you click on them to open them.

Also we should make as clear as possible what the reward asset is for each.

![image](https://user-images.githubusercontent.com/4975670/142690037-e42fe048-1965-4796-a706-5668f96deb0b.png)

**Comment by 0x4007** [comment]
![image](https://user-images.githubusercontent.com/4975670/142691472-d619c41a-ab73-4e5a-96d2-9bd04fec30f4.png)

**Comment by Zequez** [comment]
uAD-3CRV is on PoolV2 on Curve, so if you search on the PoolV3 you won't find it. The links live under the "Token Swap" section; and it's not possible to link to Curve pool directly from what I've tried. What we can do is improve the "Token Swap" section and allow members to swap the tokens directly from our UI instead of having to go through Curve or SushiSwap. That can be a separate issue. I've [added this as a suggestion on the "Token Swap" app document](https://ubiquitydao.notion.site/Token-Swap-5b73e0220f84406db20f299727bd1555); we can discuss it there and create an issue after we decided.

Now with the new sidebar we got them listed as "Liquidity Mining" for the uAD-3CRV thing, and "Yield Farming" for the USDC thing. So no longer as confusing. 

So I'm closing this.
