### ISSUE TITLE
Launch Party UI - External links

### ISSUE THREAD

**Issue by Zequez** [ubiquity/uad-ui#69]
- [x]  Link to the Twitter whitelisting request
- [x] What pre-filled message do we want?
- [x]  Link to UbiquiStick open seas NFT page
- [x]  Link to buy/sell the liquidity pool tokens
- [x]  Link to buy/sell the uAR-ETH pool

**Comment by Zequez** [comment]
@pavlovcik what do you think about a Twitter pre-filled message for when the user is not whitelisted?

Right now it's like: "@UbiquityDAO I want to be whitelisted for the  launch party https://uad.ubq.fi/launch-party"

**Comment by 0x4007** [comment]
> * [ ]   Link to the Twitter whitelisting request
> * [ ]  What pre-filled message do we want?

https://docs.google.com/document/d/1beWQE4fu0akWtpB3XbRLdD66vKIb0bgyOAgAUQyYMxk/edit

For now you can imagine that we will use "Tweeting to be eligible for the #ubiquistick NFT whitelist @UbiquityDAO"

> * [ ]   Link to UbiquiStick open seas NFT page

https://opensea.io/collection/the-ubiquistick-v3 temporary link not sure why its V3 but you can get a preview anyways

> * [ ]   Link to buy/sell the liquidity pool tokens

We will call this bonding because thats what OHM calls it.

> * [ ]   Link to buy/sell the uAR-ETH pool

**Comment by 0x4007** [comment]
> @pavlovcik what do you think about a Twitter pre-filled message for when the user is not whitelisted?
> 
> Right now it's like: "@UbiquityDAO I want to be whitelisted for the launch party https://uad.ubq.fi/launch-party"

Prefilled message dope idea. Want to use this domain: https://uar.farm

**Comment by Zequez** [comment]
If we end up deciding to create a custom domain let's create another issue to update the links; I'm closing this for now.
